version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rust-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "rust-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev" 